### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/usc-isi-i2.github.io#13]

**Comment by boschee** [comment]
ELICIT is a novel knowledge organization system that integrates concepts of causality, factual knowledge and meta-reasoning into a model-driven knowledge graph representation to provide situational awareness--especially of causal factors and relationships between them--to planners faced with complex operational environments.

ELICIT can create structured knowledge out of (and across) both structured sources (e.g. tables, spreadsheets, databases) and unstructured text sources (e.g. newswire, discussion forums, military reports). The ELICIT knowledge graph contains entities (person, organizations, etc.) and events (attacks, mergers, policy agreements, etc.) as well as links between them, all automatically derived from the input source data.

The ELICIT knowledge graph further contains *causal factors* and *causal links* between those factors. ELICIT discovers these in both structured and unstructured data, both from individual sources (e.g. _the attack led to further protests_) as well as across sources (e.g. by detecting a quantitative relationships between a time series of attacks extracted from many documents and a time series of protests extracted from a database). In the larger scope of the DARPA Causal Exploration program, these causal factors and links serve as input to causal models that help planners explore the possible impact of their actions on their operational environments.
