### ISSUE TITLE
Add Pedro's publications

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/usc-isi-i2.github.io#17]
Please add missing pubs from https://scholar.google.com/citations?hl=en&user=U1A6iBMAAAAJ&view_op=list_works&sortby=pubdate for 2017, 2016, 2015 and 2014

**Comment by szeke** [comment]
@shrev I opened my web page and the list of publications is not yet showing the pubs available in my Google Scholar link. Did you add them? 

If not, Craig said that most pubs may be in his `bib` file, so you can copy them from there.

**Comment by shrev** [comment]
@szeke I will look into the issue.
